create database bankmanagementsystem;
show databases;
use bankmanagementsystem;
create table signup(formno varchar(20) , name varchar(20), father_name varchar(20) , dob varchar(20) , gender  varchar(20) , email varchar(30) , marital varchar(20) , address varchar(40) , city varchar(25) , pincode varchar(20) , state varchar(25) );
show tables;
select * from  signup;
create table signuptwo(formno varchar(20) , sreligion varchar(20), scategory varchar(20) , sincome varchar(20) , seducational  varchar(20) , soccupation varchar(30) , span varchar(20), aadhar varchar(20) , seniorcitizen varchar(20), existingaccount varchar(20)  );
select * from  signuptwo;
create table signupthree(formno varchar(20) , accountType varchar(20), cardnumber varchar(20) , pinnumber varchar(20) ,  facility varchar(20)   );
select * from  signupthree;
alter table signupthree modify cardnumber varchar (50);
desc signupthree;
create table login( formno varchar(20) ,  cardnumber varchar(25) , pinnumber varchar(20) );
alter table signupthree modify facility varchar (50);
alter table signupthree modify facility varchar (100);
alter table signupthree modify accountType varchar (100);
select * from login;
create table bank( pin varchar(10) ,  date varchar(20) , type varchar(20) ,  amount varchar(20) );
alter table bank modify date varchar (50);
select * from bank;
alter table bank modify type varchar (50);
